global:
  scrape_interval: 5s # Jak často stahovat data (pro demo stačí 5s, v produkci 15-60s)

scrape_configs:
  - job_name: 'krematos-middleware'
    metrics_path: '/actuator/prometheus' # Kde aplikace vystavuje metriky
    static_configs:
      - targets: ['middleware-app:8080'] # Název služby z docker-compose + port